input{
    beats{
        port => 5000
    }
}

filter{
  if [container][name] == "nginx" {
    grok {
      match => { 
        "message" => '%{IPORHOST:nginx.client_ip} - %{DATA:nginx.remote_user} \[%{HTTPDATE:nginx.timestamp}\] "%{WORD:nginx.method} %{URIPATHPARAM:nginx.request} HTTP/%{NUMBER:nginx.http_version}" %{NUMBER:nginx.response_code} %{NUMBER:nginx.body_sent_bytes} "%{DATA:nginx.referrer}" "%{DATA:nginx.user_agent}"'
      }
    }
  
    date {
      match => ["nginx.timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
    
    mutate {
      add_field => {
        "service" => "nginx"
        "log_type" => "access"
      }
      convert => {
        "nginx.response_code" => "integer"
        "nginx.body_sent_bytes" => "integer"
      }
      remove_field => ["message", "agent", "ecs", "input", "log", "host", "container", "stream", "event", "tags"]
    }
  } else {
    drop {}
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-logs-%{+YYYY.MM.dd}"
  }
}