input {
  beats {
    port => 5000
  }
}

# Временный вывод для отладки - смотрим что приходит
output {
  stdout {
    codec => rubydebug
  }
  
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "raw-logs-%{+YYYY.MM.dd}"
  }
}